"""scikit-learn bayesian wrappers.

Generated from the ``BAYESIAN`` table in :mod:`tuiml.sklearn.specs`.
Registered under ``sklearn.<ClassName>`` hub keys, mirroring the native
TuiML ``bayesian`` family.
"""

# Generated by scripts/generate_sklearn_wrappers.py -- do not edit by hand.

from typing import Any, Dict, List

from tuiml.base.algorithms import Classifier, Regressor
from tuiml.sklearn._base import (
    _SklearnBackedMixin,
    sk_classifier,
    sk_regressor,
)
from tuiml.sklearn._spec import build_estimator, derive_schema

from tuiml.sklearn.specs import BAYESIAN as _SPECS

_BY_NAME = {s.name: s for s in _SPECS}


@sk_classifier(tags=['bayesian', 'naive-bayes'])
class BernoulliNB(_SklearnBackedMixin, Classifier):
    """scikit-learn BernoulliNB (hub key ``sklearn.BernoulliNB``).

    Wraps :class:`sklearn.naive_bayes.BernoulliNB`. Accepts that
    estimator's constructor parameters as keyword arguments; call
    :meth:`get_parameter_schema` for the full list with types and
    defaults derived from the installed scikit-learn.
    """

    _SPEC = _BY_NAME['BernoulliNB']

    def __init__(self, **params: Any):
        super().__init__()
        self._params = {**self._SPEC.defaults, **params}
        for key, value in self._params.items():
            setattr(self, key, value)

    def _build_estimator(self):
        """Construct the backing scikit-learn estimator."""
        return build_estimator(self._SPEC.target, self._params, 'BernoulliNB')

    @classmethod
    def get_parameter_schema(cls) -> Dict[str, Any]:
        """Return JSON Schema for constructor parameters."""
        return derive_schema(
            cls._SPEC.target, cls._SPEC.highlight, cls._SPEC.exclude
        )

    @classmethod
    def get_capabilities(cls) -> List[str]:
        """Return the capability names this wrapper supports."""
        return list(cls._SPEC.capabilities)


@sk_classifier(tags=['bayesian', 'naive-bayes', 'sklearn-extended'])
class CategoricalNB(_SklearnBackedMixin, Classifier):
    """scikit-learn CategoricalNB (hub key ``sklearn.CategoricalNB``).

    Wraps :class:`sklearn.naive_bayes.CategoricalNB`. Accepts that
    estimator's constructor parameters as keyword arguments; call
    :meth:`get_parameter_schema` for the full list with types and
    defaults derived from the installed scikit-learn.
    """

    _SPEC = _BY_NAME['CategoricalNB']

    def __init__(self, **params: Any):
        super().__init__()
        self._params = {**self._SPEC.defaults, **params}
        for key, value in self._params.items():
            setattr(self, key, value)

    def _build_estimator(self):
        """Construct the backing scikit-learn estimator."""
        return build_estimator(self._SPEC.target, self._params, 'CategoricalNB')

    @classmethod
    def get_parameter_schema(cls) -> Dict[str, Any]:
        """Return JSON Schema for constructor parameters."""
        return derive_schema(
            cls._SPEC.target, cls._SPEC.highlight, cls._SPEC.exclude
        )

    @classmethod
    def get_capabilities(cls) -> List[str]:
        """Return the capability names this wrapper supports."""
        return list(cls._SPEC.capabilities)


@sk_classifier(tags=['bayesian', 'naive-bayes', 'sklearn-extended'])
class ComplementNB(_SklearnBackedMixin, Classifier):
    """scikit-learn ComplementNB (hub key ``sklearn.ComplementNB``).

    Wraps :class:`sklearn.naive_bayes.ComplementNB`. Accepts that
    estimator's constructor parameters as keyword arguments; call
    :meth:`get_parameter_schema` for the full list with types and
    defaults derived from the installed scikit-learn.
    """

    _SPEC = _BY_NAME['ComplementNB']

    def __init__(self, **params: Any):
        super().__init__()
        self._params = {**self._SPEC.defaults, **params}
        for key, value in self._params.items():
            setattr(self, key, value)

    def _build_estimator(self):
        """Construct the backing scikit-learn estimator."""
        return build_estimator(self._SPEC.target, self._params, 'ComplementNB')

    @classmethod
    def get_parameter_schema(cls) -> Dict[str, Any]:
        """Return JSON Schema for constructor parameters."""
        return derive_schema(
            cls._SPEC.target, cls._SPEC.highlight, cls._SPEC.exclude
        )

    @classmethod
    def get_capabilities(cls) -> List[str]:
        """Return the capability names this wrapper supports."""
        return list(cls._SPEC.capabilities)


@sk_classifier(tags=['bayesian', 'naive-bayes'])
class GaussianNB(_SklearnBackedMixin, Classifier):
    """scikit-learn GaussianNB (hub key ``sklearn.GaussianNB``).

    Wraps :class:`sklearn.naive_bayes.GaussianNB`. Accepts that
    estimator's constructor parameters as keyword arguments; call
    :meth:`get_parameter_schema` for the full list with types and
    defaults derived from the installed scikit-learn.
    """

    _SPEC = _BY_NAME['GaussianNB']

    def __init__(self, **params: Any):
        super().__init__()
        self._params = {**self._SPEC.defaults, **params}
        for key, value in self._params.items():
            setattr(self, key, value)

    def _build_estimator(self):
        """Construct the backing scikit-learn estimator."""
        return build_estimator(self._SPEC.target, self._params, 'GaussianNB')

    @classmethod
    def get_parameter_schema(cls) -> Dict[str, Any]:
        """Return JSON Schema for constructor parameters."""
        return derive_schema(
            cls._SPEC.target, cls._SPEC.highlight, cls._SPEC.exclude
        )

    @classmethod
    def get_capabilities(cls) -> List[str]:
        """Return the capability names this wrapper supports."""
        return list(cls._SPEC.capabilities)


@sk_classifier(tags=['bayesian', 'gaussian-process', 'sklearn-extended'])
class GaussianProcessClassifier(_SklearnBackedMixin, Classifier):
    """scikit-learn GaussianProcessClassifier (hub key ``sklearn.GaussianProcessClassifier``).

    Wraps :class:`sklearn.gaussian_process._gpc.GaussianProcessClassifier`. Accepts that
    estimator's constructor parameters as keyword arguments; call
    :meth:`get_parameter_schema` for the full list with types and
    defaults derived from the installed scikit-learn.
    """

    _SPEC = _BY_NAME['GaussianProcessClassifier']

    def __init__(self, **params: Any):
        super().__init__()
        self._params = {**self._SPEC.defaults, **params}
        for key, value in self._params.items():
            setattr(self, key, value)

    def _build_estimator(self):
        """Construct the backing scikit-learn estimator."""
        return build_estimator(self._SPEC.target, self._params, 'GaussianProcessClassifier')

    @classmethod
    def get_parameter_schema(cls) -> Dict[str, Any]:
        """Return JSON Schema for constructor parameters."""
        return derive_schema(
            cls._SPEC.target, cls._SPEC.highlight, cls._SPEC.exclude
        )

    @classmethod
    def get_capabilities(cls) -> List[str]:
        """Return the capability names this wrapper supports."""
        return list(cls._SPEC.capabilities)


@sk_classifier(tags=['bayesian', 'naive-bayes'])
class MultinomialNB(_SklearnBackedMixin, Classifier):
    """scikit-learn MultinomialNB (hub key ``sklearn.MultinomialNB``).

    Wraps :class:`sklearn.naive_bayes.MultinomialNB`. Accepts that
    estimator's constructor parameters as keyword arguments; call
    :meth:`get_parameter_schema` for the full list with types and
    defaults derived from the installed scikit-learn.
    """

    _SPEC = _BY_NAME['MultinomialNB']

    def __init__(self, **params: Any):
        super().__init__()
        self._params = {**self._SPEC.defaults, **params}
        for key, value in self._params.items():
            setattr(self, key, value)

    def _build_estimator(self):
        """Construct the backing scikit-learn estimator."""
        return build_estimator(self._SPEC.target, self._params, 'MultinomialNB')

    @classmethod
    def get_parameter_schema(cls) -> Dict[str, Any]:
        """Return JSON Schema for constructor parameters."""
        return derive_schema(
            cls._SPEC.target, cls._SPEC.highlight, cls._SPEC.exclude
        )

    @classmethod
    def get_capabilities(cls) -> List[str]:
        """Return the capability names this wrapper supports."""
        return list(cls._SPEC.capabilities)


@sk_regressor(tags=['bayesian', 'gaussian-process', 'sklearn-extended'])
class GaussianProcessRegressor(_SklearnBackedMixin, Regressor):
    """scikit-learn GaussianProcessRegressor (hub key ``sklearn.GaussianProcessRegressor``).

    Wraps :class:`sklearn.gaussian_process._gpr.GaussianProcessRegressor`. Accepts that
    estimator's constructor parameters as keyword arguments; call
    :meth:`get_parameter_schema` for the full list with types and
    defaults derived from the installed scikit-learn.
    """

    _SPEC = _BY_NAME['GaussianProcessRegressor']

    def __init__(self, **params: Any):
        super().__init__()
        self._params = {**self._SPEC.defaults, **params}
        for key, value in self._params.items():
            setattr(self, key, value)

    def _build_estimator(self):
        """Construct the backing scikit-learn estimator."""
        return build_estimator(self._SPEC.target, self._params, 'GaussianProcessRegressor')

    @classmethod
    def get_parameter_schema(cls) -> Dict[str, Any]:
        """Return JSON Schema for constructor parameters."""
        return derive_schema(
            cls._SPEC.target, cls._SPEC.highlight, cls._SPEC.exclude
        )

    @classmethod
    def get_capabilities(cls) -> List[str]:
        """Return the capability names this wrapper supports."""
        return list(cls._SPEC.capabilities)


__all__ = ['BernoulliNB', 'CategoricalNB', 'ComplementNB', 'GaussianNB', 'GaussianProcessClassifier', 'MultinomialNB', 'GaussianProcessRegressor']
