"""Declarative table of every wrapped scikit-learn estimator.

This module is the source of truth for the wrapper modules in this package.
To add an estimator, add a row here and a matching wrapper class in the
corresponding family module.

Currently 154 estimators across 14 families. Rows with
``tier=1`` are curated and surfaced by default; ``tier=2`` rows are also
tagged ``sklearn-extended`` so search and listings can filter them out.
"""


from tuiml.sklearn._spec import SklearnSpec as S

#: anomaly.py -- 5 estimators
ANOMALY = [
    S(
        name='EllipticEnvelope',
        target='sklearn.covariance._elliptic_envelope:EllipticEnvelope',
        kind='classifier',
        tags=('anomaly', 'covariance', 'anomaly-detection'),
        capabilities=('numeric', 'multiclass'),
        tier=1,
    ),
    S(
        name='IsolationForest',
        target='sklearn.ensemble._iforest:IsolationForest',
        kind='classifier',
        tags=('anomaly', 'ensemble', 'anomaly-detection'),
        capabilities=('numeric', 'multiclass'),
        highlight=('n_estimators', 'contamination', 'random_state'),
        tier=1,
    ),
    S(
        name='LocalOutlierFactor',
        target='sklearn.neighbors._lof:LocalOutlierFactor',
        kind='classifier',
        tags=('anomaly', 'neighbors', 'anomaly-detection'),
        capabilities=('numeric', 'multiclass'),
        defaults={'novelty': True},
        highlight=('n_neighbors', 'contamination'),
        tier=1,
    ),
    S(
        name='OneClassSVM',
        target='sklearn.svm._classes:OneClassSVM',
        kind='classifier',
        tags=('anomaly', 'svm', 'anomaly-detection'),
        capabilities=('numeric', 'multiclass'),
        highlight=('kernel', 'nu', 'gamma'),
        tier=1,
    ),
    S(
        name='SGDOneClassSVM',
        target='sklearn.linear_model._stochastic_gradient:SGDOneClassSVM',
        kind='classifier',
        tags=('anomaly', 'linear-model', 'anomaly-detection', 'svm'),
        capabilities=('numeric', 'multiclass'),
        tier=2,
    ),
]

#: bayesian.py -- 7 estimators
BAYESIAN = [
    S(
        name='BernoulliNB',
        target='sklearn.naive_bayes:BernoulliNB',
        kind='classifier',
        tags=('bayesian', 'naive-bayes'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=1,
    ),
    S(
        name='CategoricalNB',
        target='sklearn.naive_bayes:CategoricalNB',
        kind='classifier',
        tags=('bayesian', 'naive-bayes'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='ComplementNB',
        target='sklearn.naive_bayes:ComplementNB',
        kind='classifier',
        tags=('bayesian', 'naive-bayes'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='GaussianNB',
        target='sklearn.naive_bayes:GaussianNB',
        kind='classifier',
        tags=('bayesian', 'naive-bayes'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=1,
    ),
    S(
        name='GaussianProcessClassifier',
        target='sklearn.gaussian_process._gpc:GaussianProcessClassifier',
        kind='classifier',
        tags=('bayesian', 'gaussian-process'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='MultinomialNB',
        target='sklearn.naive_bayes:MultinomialNB',
        kind='classifier',
        tags=('bayesian', 'naive-bayes'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=1,
    ),
    S(
        name='GaussianProcessRegressor',
        target='sklearn.gaussian_process._gpr:GaussianProcessRegressor',
        kind='regressor',
        tags=('bayesian', 'gaussian-process'),
        capabilities=('numeric',),
        tier=2,
    ),
]

#: clustering.py -- 13 estimators
CLUSTERING = [
    S(
        name='AffinityPropagation',
        target='sklearn.cluster._affinity_propagation:AffinityPropagation',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='AgglomerativeClustering',
        target='sklearn.cluster._agglomerative:AgglomerativeClustering',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        highlight=('n_clusters', 'linkage', 'metric'),
        tier=1,
    ),
    S(
        name='BayesianGaussianMixture',
        target='sklearn.mixture._bayesian_mixture:BayesianGaussianMixture',
        kind='clusterer',
        tags=('clustering', 'mixture'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='Birch',
        target='sklearn.cluster._birch:Birch',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='BisectingKMeans',
        target='sklearn.cluster._bisect_k_means:BisectingKMeans',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='DBSCAN',
        target='sklearn.cluster._dbscan:DBSCAN',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        highlight=('eps', 'min_samples', 'metric'),
        tier=1,
    ),
    S(
        name='GaussianMixture',
        target='sklearn.mixture._gaussian_mixture:GaussianMixture',
        kind='clusterer',
        tags=('clustering', 'mixture'),
        capabilities=('numeric',),
        highlight=('n_components', 'covariance_type', 'random_state'),
        tier=1,
    ),
    S(
        name='HDBSCAN',
        target='sklearn.cluster._hdbscan.hdbscan:HDBSCAN',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='KMeans',
        target='sklearn.cluster._kmeans:KMeans',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        highlight=('n_clusters', 'init', 'n_init', 'random_state'),
        tier=1,
    ),
    S(
        name='MeanShift',
        target='sklearn.cluster._mean_shift:MeanShift',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='MiniBatchKMeans',
        target='sklearn.cluster._kmeans:MiniBatchKMeans',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='OPTICS',
        target='sklearn.cluster._optics:OPTICS',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SpectralClustering',
        target='sklearn.cluster._spectral:SpectralClustering',
        kind='clusterer',
        tags=('clustering', 'cluster'),
        capabilities=('numeric',),
        tier=1,
    ),
]

#: ensemble.py -- 13 estimators
ENSEMBLE = [
    S(
        name='AdaBoostClassifier',
        target='sklearn.ensemble._weight_boosting:AdaBoostClassifier',
        kind='classifier',
        tags=('ensemble',),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=1,
    ),
    S(
        name='BaggingClassifier',
        target='sklearn.ensemble._bagging:BaggingClassifier',
        kind='classifier',
        tags=('ensemble',),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=1,
    ),
    S(
        name='ExtraTreesClassifier',
        target='sklearn.ensemble._forest:ExtraTreesClassifier',
        kind='classifier',
        tags=('ensemble', 'tree'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('n_estimators', 'max_depth', 'random_state'),
        tier=1,
    ),
    S(
        name='GradientBoostingClassifier',
        target='sklearn.ensemble._gb:GradientBoostingClassifier',
        kind='classifier',
        tags=('ensemble', 'gradient-boosting'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('n_estimators', 'learning_rate', 'max_depth'),
        tier=1,
    ),
    S(
        name='HistGradientBoostingClassifier',
        target='sklearn.ensemble._hist_gradient_boosting.gradient_boosting:HistGradientBoostingClassifier',
        kind='classifier',
        tags=('ensemble', 'gradient-boosting'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('learning_rate', 'max_iter', 'max_depth'),
        tier=1,
    ),
    S(
        name='RandomForestClassifier',
        target='sklearn.ensemble._forest:RandomForestClassifier',
        kind='classifier',
        tags=('ensemble',),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('n_estimators', 'max_depth', 'random_state'),
        tier=1,
    ),
    S(
        name='AdaBoostRegressor',
        target='sklearn.ensemble._weight_boosting:AdaBoostRegressor',
        kind='regressor',
        tags=('ensemble',),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='BaggingRegressor',
        target='sklearn.ensemble._bagging:BaggingRegressor',
        kind='regressor',
        tags=('ensemble',),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='ExtraTreesRegressor',
        target='sklearn.ensemble._forest:ExtraTreesRegressor',
        kind='regressor',
        tags=('ensemble', 'tree'),
        capabilities=('numeric',),
        highlight=('n_estimators', 'max_depth', 'random_state'),
        tier=1,
    ),
    S(
        name='GradientBoostingRegressor',
        target='sklearn.ensemble._gb:GradientBoostingRegressor',
        kind='regressor',
        tags=('ensemble', 'gradient-boosting'),
        capabilities=('numeric',),
        highlight=('n_estimators', 'learning_rate', 'max_depth'),
        tier=1,
    ),
    S(
        name='HistGradientBoostingRegressor',
        target='sklearn.ensemble._hist_gradient_boosting.gradient_boosting:HistGradientBoostingRegressor',
        kind='regressor',
        tags=('ensemble', 'gradient-boosting'),
        capabilities=('numeric',),
        highlight=('learning_rate', 'max_iter', 'max_depth'),
        tier=1,
    ),
    S(
        name='RandomForestRegressor',
        target='sklearn.ensemble._forest:RandomForestRegressor',
        kind='regressor',
        tags=('ensemble',),
        capabilities=('numeric',),
        highlight=('n_estimators', 'max_depth', 'random_state'),
        tier=1,
    ),
    S(
        name='RandomTreesEmbedding',
        target='sklearn.ensemble._forest:RandomTreesEmbedding',
        kind='transformer',
        tags=('ensemble', 'tree'),
        capabilities=('numeric',),
        tier=2,
    ),
]

#: features/extraction.py -- 22 estimators
FEATURES_EXTRACTION = [
    S(
        name='AdditiveChi2Sampler',
        target='sklearn.kernel_approximation:AdditiveChi2Sampler',
        kind='feature_extractor',
        tags=('extraction', 'kernel-approximation'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='DictionaryLearning',
        target='sklearn.decomposition._dict_learning:DictionaryLearning',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='FactorAnalysis',
        target='sklearn.decomposition._factor_analysis:FactorAnalysis',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='FastICA',
        target='sklearn.decomposition._fastica:FastICA',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        highlight=('n_components', 'random_state'),
        tier=1,
    ),
    S(
        name='GaussianRandomProjection',
        target='sklearn.random_projection:GaussianRandomProjection',
        kind='feature_extractor',
        tags=('extraction', 'random-projection'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='IncrementalPCA',
        target='sklearn.decomposition._incremental_pca:IncrementalPCA',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='Isomap',
        target='sklearn.manifold._isomap:Isomap',
        kind='feature_extractor',
        tags=('extraction', 'manifold'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='KernelPCA',
        target='sklearn.decomposition._kernel_pca:KernelPCA',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        highlight=('n_components', 'kernel', 'gamma'),
        tier=1,
    ),
    S(
        name='LatentDirichletAllocation',
        target='sklearn.decomposition._lda:LatentDirichletAllocation',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='LocallyLinearEmbedding',
        target='sklearn.manifold._locally_linear:LocallyLinearEmbedding',
        kind='feature_extractor',
        tags=('extraction', 'manifold'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='MiniBatchDictionaryLearning',
        target='sklearn.decomposition._dict_learning:MiniBatchDictionaryLearning',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='MiniBatchNMF',
        target='sklearn.decomposition._nmf:MiniBatchNMF',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='MiniBatchSparsePCA',
        target='sklearn.decomposition._sparse_pca:MiniBatchSparsePCA',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='NMF',
        target='sklearn.decomposition._nmf:NMF',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        highlight=('n_components', 'init', 'random_state'),
        tier=1,
    ),
    S(
        name='Nystroem',
        target='sklearn.kernel_approximation:Nystroem',
        kind='feature_extractor',
        tags=('extraction', 'kernel-approximation'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='PCAExtractor',
        target='sklearn.decomposition._pca:PCA',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        highlight=('n_components', 'whiten', 'random_state'),
        tier=1,
    ),
    S(
        name='PolynomialCountSketch',
        target='sklearn.kernel_approximation:PolynomialCountSketch',
        kind='feature_extractor',
        tags=('extraction', 'kernel-approximation'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='RBFSampler',
        target='sklearn.kernel_approximation:RBFSampler',
        kind='feature_extractor',
        tags=('extraction', 'kernel-approximation'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SkewedChi2Sampler',
        target='sklearn.kernel_approximation:SkewedChi2Sampler',
        kind='feature_extractor',
        tags=('extraction', 'kernel-approximation'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SparsePCA',
        target='sklearn.decomposition._sparse_pca:SparsePCA',
        kind='feature_extractor',
        tags=('extraction', 'decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SparseRandomProjection',
        target='sklearn.random_projection:SparseRandomProjection',
        kind='feature_extractor',
        tags=('extraction', 'random-projection'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='TruncatedSVD',
        target='sklearn.decomposition._truncated_svd:TruncatedSVD',
        kind='feature_extractor',
        tags=('extraction', 'decomposition', 'svm'),
        capabilities=('numeric',),
        highlight=('n_components', 'algorithm', 'random_state'),
        tier=1,
    ),
]

#: features/selection.py -- 7 estimators
FEATURES_SELECTION = [
    S(
        name='GenericUnivariateSelect',
        target='sklearn.feature_selection._univariate_selection:GenericUnivariateSelect',
        kind='feature_selector',
        tags=('selection', 'feature-selection'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SelectFdr',
        target='sklearn.feature_selection._univariate_selection:SelectFdr',
        kind='feature_selector',
        tags=('selection', 'feature-selection'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SelectFpr',
        target='sklearn.feature_selection._univariate_selection:SelectFpr',
        kind='feature_selector',
        tags=('selection', 'feature-selection'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SelectFwe',
        target='sklearn.feature_selection._univariate_selection:SelectFwe',
        kind='feature_selector',
        tags=('selection', 'feature-selection'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SelectKBest',
        target='sklearn.feature_selection._univariate_selection:SelectKBest',
        kind='feature_selector',
        tags=('selection', 'feature-selection'),
        capabilities=('numeric',),
        highlight=('k', 'score_func'),
        tier=1,
    ),
    S(
        name='SelectPercentile',
        target='sklearn.feature_selection._univariate_selection:SelectPercentile',
        kind='feature_selector',
        tags=('selection', 'feature-selection'),
        capabilities=('numeric',),
        highlight=('percentile', 'score_func'),
        tier=1,
    ),
    S(
        name='VarianceThreshold',
        target='sklearn.feature_selection._variance_threshold:VarianceThreshold',
        kind='feature_selector',
        tags=('selection', 'feature-selection'),
        capabilities=('numeric',),
        highlight=('threshold',),
        tier=1,
    ),
]

#: linear.py -- 40 estimators
LINEAR = [
    S(
        name='DummyClassifier',
        target='sklearn.dummy:DummyClassifier',
        kind='classifier',
        tags=('linear', 'dummy'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='LabelPropagation',
        target='sklearn.semi_supervised._label_propagation:LabelPropagation',
        kind='classifier',
        tags=('linear', 'semi-supervised'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='LabelSpreading',
        target='sklearn.semi_supervised._label_propagation:LabelSpreading',
        kind='classifier',
        tags=('linear', 'semi-supervised'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='LinearDiscriminantAnalysis',
        target='sklearn.discriminant_analysis:LinearDiscriminantAnalysis',
        kind='classifier',
        tags=('linear', 'discriminant-analysis'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='LogisticRegression',
        target='sklearn.linear_model._logistic:LogisticRegression',
        kind='classifier',
        tags=('linear', 'linear-model'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('C', 'penalty', 'solver', 'max_iter'),
        tier=1,
    ),
    S(
        name='LogisticRegressionCV',
        target='sklearn.linear_model._logistic:LogisticRegressionCV',
        kind='classifier',
        tags=('linear', 'linear-model'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='PassiveAggressiveClassifier',
        target='sklearn.linear_model._passive_aggressive:PassiveAggressiveClassifier',
        kind='classifier',
        tags=('linear', 'linear-model'),
        capabilities=('numeric', 'multiclass'),
        tier=2,
    ),
    S(
        name='Perceptron',
        target='sklearn.linear_model._perceptron:Perceptron',
        kind='classifier',
        tags=('linear', 'linear-model'),
        capabilities=('numeric', 'multiclass'),
        tier=2,
    ),
    S(
        name='QuadraticDiscriminantAnalysis',
        target='sklearn.discriminant_analysis:QuadraticDiscriminantAnalysis',
        kind='classifier',
        tags=('linear', 'discriminant-analysis'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='RidgeClassifier',
        target='sklearn.linear_model._ridge:RidgeClassifier',
        kind='classifier',
        tags=('linear', 'linear-model'),
        capabilities=('numeric', 'multiclass'),
        tier=2,
    ),
    S(
        name='RidgeClassifierCV',
        target='sklearn.linear_model._ridge:RidgeClassifierCV',
        kind='classifier',
        tags=('linear', 'linear-model'),
        capabilities=('numeric', 'multiclass'),
        tier=2,
    ),
    S(
        name='SGDClassifier',
        target='sklearn.linear_model._stochastic_gradient:SGDClassifier',
        kind='classifier',
        tags=('linear', 'linear-model'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=1,
    ),
    S(
        name='ARDRegression',
        target='sklearn.linear_model._bayes:ARDRegression',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='BayesianRidge',
        target='sklearn.linear_model._bayes:BayesianRidge',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='DummyRegressor',
        target='sklearn.dummy:DummyRegressor',
        kind='regressor',
        tags=('linear', 'dummy'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='ElasticNet',
        target='sklearn.linear_model._coordinate_descent:ElasticNet',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        highlight=('alpha', 'l1_ratio'),
        tier=1,
    ),
    S(
        name='ElasticNetCV',
        target='sklearn.linear_model._coordinate_descent:ElasticNetCV',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='GammaRegressor',
        target='sklearn.linear_model._glm.glm:GammaRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='HuberRegressor',
        target='sklearn.linear_model._huber:HuberRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='KernelRidge',
        target='sklearn.kernel_ridge:KernelRidge',
        kind='regressor',
        tags=('linear', 'kernel-ridge'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='Lars',
        target='sklearn.linear_model._least_angle:Lars',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='LarsCV',
        target='sklearn.linear_model._least_angle:LarsCV',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='Lasso',
        target='sklearn.linear_model._coordinate_descent:Lasso',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        highlight=('alpha', 'max_iter'),
        tier=1,
    ),
    S(
        name='LassoCV',
        target='sklearn.linear_model._coordinate_descent:LassoCV',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='LassoLars',
        target='sklearn.linear_model._least_angle:LassoLars',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='LassoLarsCV',
        target='sklearn.linear_model._least_angle:LassoLarsCV',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='LassoLarsIC',
        target='sklearn.linear_model._least_angle:LassoLarsIC',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='LinearRegression',
        target='sklearn.linear_model._base:LinearRegression',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='OrthogonalMatchingPursuit',
        target='sklearn.linear_model._omp:OrthogonalMatchingPursuit',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='OrthogonalMatchingPursuitCV',
        target='sklearn.linear_model._omp:OrthogonalMatchingPursuitCV',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='PLSRegression',
        target='sklearn.cross_decomposition._pls:PLSRegression',
        kind='regressor',
        tags=('linear', 'cross-decomposition'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='PassiveAggressiveRegressor',
        target='sklearn.linear_model._passive_aggressive:PassiveAggressiveRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='PoissonRegressor',
        target='sklearn.linear_model._glm.glm:PoissonRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='QuantileRegressor',
        target='sklearn.linear_model._quantile:QuantileRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='RANSACRegressor',
        target='sklearn.linear_model._ransac:RANSACRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='Ridge',
        target='sklearn.linear_model._ridge:Ridge',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        highlight=('alpha', 'solver'),
        tier=1,
    ),
    S(
        name='RidgeCV',
        target='sklearn.linear_model._ridge:RidgeCV',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SGDRegressor',
        target='sklearn.linear_model._stochastic_gradient:SGDRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='TheilSenRegressor',
        target='sklearn.linear_model._theil_sen:TheilSenRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='TweedieRegressor',
        target='sklearn.linear_model._glm.glm:TweedieRegressor',
        kind='regressor',
        tags=('linear', 'linear-model'),
        capabilities=('numeric',),
        tier=2,
    ),
]

#: neighbors.py -- 8 estimators
NEIGHBORS = [
    S(
        name='KNeighborsClassifier',
        target='sklearn.neighbors._classification:KNeighborsClassifier',
        kind='classifier',
        tags=('neighbors', 'instance-based'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('n_neighbors', 'weights', 'metric'),
        tier=1,
    ),
    S(
        name='NearestCentroid',
        target='sklearn.neighbors._nearest_centroid:NearestCentroid',
        kind='classifier',
        tags=('neighbors',),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='RadiusNeighborsClassifier',
        target='sklearn.neighbors._classification:RadiusNeighborsClassifier',
        kind='classifier',
        tags=('neighbors', 'instance-based'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='KNeighborsRegressor',
        target='sklearn.neighbors._regression:KNeighborsRegressor',
        kind='regressor',
        tags=('neighbors', 'instance-based'),
        capabilities=('numeric',),
        highlight=('n_neighbors', 'weights', 'metric'),
        tier=1,
    ),
    S(
        name='RadiusNeighborsRegressor',
        target='sklearn.neighbors._regression:RadiusNeighborsRegressor',
        kind='regressor',
        tags=('neighbors', 'instance-based'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='KNeighborsTransformer',
        target='sklearn.neighbors._graph:KNeighborsTransformer',
        kind='transformer',
        tags=('neighbors', 'instance-based'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='NeighborhoodComponentsAnalysis',
        target='sklearn.neighbors._nca:NeighborhoodComponentsAnalysis',
        kind='transformer',
        tags=('neighbors',),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='RadiusNeighborsTransformer',
        target='sklearn.neighbors._graph:RadiusNeighborsTransformer',
        kind='transformer',
        tags=('neighbors', 'instance-based'),
        capabilities=('numeric',),
        tier=2,
    ),
]

#: neural.py -- 3 estimators
NEURAL = [
    S(
        name='MLPClassifier',
        target='sklearn.neural_network._multilayer_perceptron:MLPClassifier',
        kind='classifier',
        tags=('neural', 'neural-network'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('hidden_layer_sizes', 'activation', 'max_iter'),
        tier=1,
    ),
    S(
        name='MLPRegressor',
        target='sklearn.neural_network._multilayer_perceptron:MLPRegressor',
        kind='regressor',
        tags=('neural', 'neural-network'),
        capabilities=('numeric',),
        highlight=('hidden_layer_sizes', 'activation', 'max_iter'),
        tier=1,
    ),
    S(
        name='BernoulliRBM',
        target='sklearn.neural_network._rbm:BernoulliRBM',
        kind='transformer',
        tags=('neural', 'neural-network'),
        capabilities=('numeric',),
        tier=2,
    ),
]

#: preprocessing/imputation.py -- 4 estimators
PREPROCESSING_IMPUTATION = [
    S(
        name='IterativeImputer',
        target='sklearn.impute._iterative:IterativeImputer',
        kind='transformer',
        tags=('imputation', 'impute'),
        capabilities=('numeric',),
        highlight=('max_iter', 'random_state'),
        tier=1,
        builder='iterative_imputer',
    ),
    S(
        name='KNNImputer',
        target='sklearn.impute._knn:KNNImputer',
        kind='transformer',
        tags=('imputation', 'impute'),
        capabilities=('numeric',),
        highlight=('n_neighbors', 'weights'),
        tier=1,
    ),
    S(
        name='MissingIndicator',
        target='sklearn.impute._base:MissingIndicator',
        kind='transformer',
        tags=('imputation', 'impute'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SimpleImputer',
        target='sklearn.impute._base:SimpleImputer',
        kind='transformer',
        tags=('imputation', 'impute'),
        capabilities=('numeric',),
        highlight=('strategy', 'fill_value'),
        tier=1,
    ),
]

#: preprocessing/scaling.py -- 15 estimators
PREPROCESSING_SCALING = [
    S(
        name='Binarizer',
        target='sklearn.preprocessing._data:Binarizer',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='FunctionTransformer',
        target='sklearn.preprocessing._function_transformer:FunctionTransformer',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='KBinsDiscretizer',
        target='sklearn.preprocessing._discretization:KBinsDiscretizer',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        highlight=('n_bins', 'encode', 'strategy'),
        tier=1,
    ),
    S(
        name='MaxAbsScaler',
        target='sklearn.preprocessing._data:MaxAbsScaler',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='MinMaxScaler',
        target='sklearn.preprocessing._data:MinMaxScaler',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        highlight=('feature_range',),
        tier=1,
    ),
    S(
        name='Normalizer',
        target='sklearn.preprocessing._data:Normalizer',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='OneHotEncoder',
        target='sklearn.preprocessing._encoders:OneHotEncoder',
        kind='transformer',
        tags=('scaling', 'preprocessing', 'encoding'),
        capabilities=('numeric',),
        highlight=('handle_unknown', 'drop', 'sparse_output'),
        tier=1,
    ),
    S(
        name='OrdinalEncoder',
        target='sklearn.preprocessing._encoders:OrdinalEncoder',
        kind='transformer',
        tags=('scaling', 'preprocessing', 'encoding'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='PolynomialFeatures',
        target='sklearn.preprocessing._polynomial:PolynomialFeatures',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        highlight=('degree', 'interaction_only', 'include_bias'),
        tier=1,
    ),
    S(
        name='PowerTransformer',
        target='sklearn.preprocessing._data:PowerTransformer',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='QuantileTransformer',
        target='sklearn.preprocessing._data:QuantileTransformer',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='RobustScaler',
        target='sklearn.preprocessing._data:RobustScaler',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        highlight=('with_centering', 'with_scaling', 'quantile_range'),
        tier=1,
    ),
    S(
        name='SplineTransformer',
        target='sklearn.preprocessing._polynomial:SplineTransformer',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='StandardScaler',
        target='sklearn.preprocessing._data:StandardScaler',
        kind='transformer',
        tags=('scaling', 'preprocessing'),
        capabilities=('numeric',),
        highlight=('with_mean', 'with_std'),
        tier=1,
    ),
    S(
        name='TargetEncoder',
        target='sklearn.preprocessing._target_encoder:TargetEncoder',
        kind='transformer',
        tags=('scaling', 'preprocessing', 'encoding'),
        capabilities=('numeric',),
        tier=2,
    ),
]

#: preprocessing/text.py -- 7 estimators
PREPROCESSING_TEXT = [
    S(
        name='CountVectorizer',
        target='sklearn.feature_extraction.text:CountVectorizer',
        kind='transformer',
        tags=('text', 'feature-extraction'),
        capabilities=('numeric',),
        highlight=('max_features', 'ngram_range', 'stop_words'),
        tier=1,
    ),
    S(
        name='DictVectorizer',
        target='sklearn.feature_extraction._dict_vectorizer:DictVectorizer',
        kind='transformer',
        tags=('text', 'feature-extraction'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='FeatureHasher',
        target='sklearn.feature_extraction._hash:FeatureHasher',
        kind='transformer',
        tags=('text', 'feature-extraction'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='HashingVectorizer',
        target='sklearn.feature_extraction.text:HashingVectorizer',
        kind='transformer',
        tags=('text', 'feature-extraction'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='PatchExtractor',
        target='sklearn.feature_extraction.image:PatchExtractor',
        kind='transformer',
        tags=('text', 'feature-extraction'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='TfidfTransformer',
        target='sklearn.feature_extraction.text:TfidfTransformer',
        kind='transformer',
        tags=('text', 'feature-extraction'),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='TfidfVectorizer',
        target='sklearn.feature_extraction.text:TfidfVectorizer',
        kind='transformer',
        tags=('text', 'feature-extraction'),
        capabilities=('numeric',),
        highlight=('max_features', 'ngram_range', 'stop_words'),
        tier=1,
    ),
]

#: svm.py -- 6 estimators
SVM = [
    S(
        name='LinearSVC',
        target='sklearn.svm._classes:LinearSVC',
        kind='classifier',
        tags=('svm',),
        capabilities=('numeric', 'multiclass'),
        highlight=('C', 'loss', 'max_iter'),
        tier=1,
    ),
    S(
        name='NuSVC',
        target='sklearn.svm._classes:NuSVC',
        kind='classifier',
        tags=('svm',),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='SVC',
        target='sklearn.svm._classes:SVC',
        kind='classifier',
        tags=('svm',),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        defaults={'probability': True},
        highlight=('C', 'kernel', 'gamma', 'probability'),
        exclude=('kernel_precomputed',),
        tier=1,
        builder='svc_with_optional_calibration',
    ),
    S(
        name='LinearSVR',
        target='sklearn.svm._classes:LinearSVR',
        kind='regressor',
        tags=('svm',),
        capabilities=('numeric',),
        tier=1,
    ),
    S(
        name='NuSVR',
        target='sklearn.svm._classes:NuSVR',
        kind='regressor',
        tags=('svm',),
        capabilities=('numeric',),
        tier=2,
    ),
    S(
        name='SVR',
        target='sklearn.svm._classes:SVR',
        kind='regressor',
        tags=('svm',),
        capabilities=('numeric',),
        highlight=('C', 'kernel', 'epsilon'),
        tier=1,
    ),
]

#: trees.py -- 4 estimators
TREES = [
    S(
        name='DecisionTreeClassifier',
        target='sklearn.tree._classes:DecisionTreeClassifier',
        kind='classifier',
        tags=('trees', 'tree'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        highlight=('criterion', 'max_depth', 'random_state'),
        tier=1,
    ),
    S(
        name='ExtraTreeClassifier',
        target='sklearn.tree._classes:ExtraTreeClassifier',
        kind='classifier',
        tags=('trees', 'tree'),
        capabilities=('numeric', 'multiclass', 'probabilities'),
        tier=2,
    ),
    S(
        name='DecisionTreeRegressor',
        target='sklearn.tree._classes:DecisionTreeRegressor',
        kind='regressor',
        tags=('trees', 'tree'),
        capabilities=('numeric',),
        highlight=('criterion', 'max_depth', 'random_state'),
        tier=1,
    ),
    S(
        name='ExtraTreeRegressor',
        target='sklearn.tree._classes:ExtraTreeRegressor',
        kind='regressor',
        tags=('trees', 'tree'),
        capabilities=('numeric',),
        tier=2,
    ),
]

#: Every family table, keyed by generated module path.
FAMILIES = {
    'anomaly': ANOMALY,
    'bayesian': BAYESIAN,
    'clustering': CLUSTERING,
    'ensemble': ENSEMBLE,
    'features/extraction': FEATURES_EXTRACTION,
    'features/selection': FEATURES_SELECTION,
    'linear': LINEAR,
    'neighbors': NEIGHBORS,
    'neural': NEURAL,
    'preprocessing/imputation': PREPROCESSING_IMPUTATION,
    'preprocessing/scaling': PREPROCESSING_SCALING,
    'preprocessing/text': PREPROCESSING_TEXT,
    'svm': SVM,
    'trees': TREES,
}

#: Estimators deliberately not wrapped, with the reason. Recorded so the
#: gap is visible rather than silent; see the module docstring.
NOT_WRAPPED = {
    'CCA': 'cross-decomposition, requires multi-column y',
    'CalibratedClassifierCV': "module 'calibration' not mapped to a family",
    'ClassicalMDS': 'no TuiML component kind',
    'ClassifierChain': "needs required arg(s) ['estimator']",
    'ColumnTransformer': "needs required arg(s) ['transformers']",
    'EmpiricalCovariance': 'no TuiML component kind',
    'FeatureAgglomeration': 'n_clusters is bounded by n_features, not n_samples',
    'FeatureUnion': "needs required arg(s) ['transformer_list']",
    'FixedThresholdClassifier': "needs required arg(s) ['estimator']",
    'FrozenEstimator': "needs required arg(s) ['estimator']",
    'GraphicalLasso': 'no TuiML component kind',
    'GraphicalLassoCV': 'no TuiML component kind',
    'GridSearchCV': "needs required arg(s) ['estimator', 'param_grid']",
    'IsotonicRegression': 'requires 1-D X',
    'KernelCenterer': 'operates on a kernel matrix, not a feature matrix',
    'KernelDensity': 'no TuiML component kind',
    'LabelBinarizer': 'transforms labels, signature is fit(y) not fit(X, y)',
    'LabelEncoder': 'transforms labels, signature is fit(y) not fit(X, y)',
    'LedoitWolf': 'no TuiML component kind',
    'MDS': 'no TuiML component kind',
    'MinCovDet': 'no TuiML component kind',
    'MultiLabelBinarizer': 'transforms labels, signature is fit(y) not fit(X, y)',
    'MultiOutputClassifier': "needs required arg(s) ['estimator']",
    'MultiOutputRegressor': "needs required arg(s) ['estimator']",
    'MultiTaskElasticNet': 'requires 2-D (multi-output) y',
    'MultiTaskElasticNetCV': 'requires 2-D (multi-output) y',
    'MultiTaskLasso': 'requires 2-D (multi-output) y',
    'MultiTaskLassoCV': 'requires 2-D (multi-output) y',
    'NearestNeighbors': 'no TuiML component kind',
    'OAS': 'no TuiML component kind',
    'OneVsOneClassifier': "needs required arg(s) ['estimator']",
    'OneVsRestClassifier': "needs required arg(s) ['estimator']",
    'OutputCodeClassifier': "needs required arg(s) ['estimator']",
    'PLSCanonical': 'cross-decomposition, requires multi-column y',
    'PLSSVD': 'cross-decomposition, requires multi-column y',
    'Pipeline': "needs required arg(s) ['steps']",
    'RFE': "needs required arg(s) ['estimator']",
    'RFECV': "needs required arg(s) ['estimator']",
    'RandomizedSearchCV': "needs required arg(s) ['estimator', 'param_distributions']",
    'RegressorChain': "needs required arg(s) ['estimator']",
    'SelectFromModel': "needs required arg(s) ['estimator']",
    'SelfTrainingClassifier': 'meta-estimator, requires an inner estimator',
    'SequentialFeatureSelector': "needs required arg(s) ['estimator']",
    'ShrunkCovariance': 'no TuiML component kind',
    'SparseCoder': "needs required arg(s) ['dictionary']",
    'SpectralBiclustering': 'no TuiML component kind',
    'SpectralCoclustering': 'no TuiML component kind',
    'SpectralEmbedding': 'no TuiML component kind',
    'StackingClassifier': "needs required arg(s) ['estimators']",
    'StackingRegressor': "needs required arg(s) ['estimators']",
    'TSNE': 'no TuiML component kind',
    'TransformedTargetRegressor': "module 'compose' not mapped to a family",
    'TunedThresholdClassifierCV': "needs required arg(s) ['estimator']",
    'VotingClassifier': "needs required arg(s) ['estimators']",
    'VotingRegressor': "needs required arg(s) ['estimators']",
}
